version: '2'
services:
  ### MariaDB Container
  mysql:
    build:
      context: ./mariadb
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped
  kafka:
    build:
      context: ./kafka
    ports:
      - "9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  mysql-master:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    container_name: mysql-master
    ports:
      - "9000:3306"
    volumes:
      - ./mysql/master/config_file.cnf:/etc/mysql/conf.d/config_file.cnf
  mysql-slave-1:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    container_name: mysql-slave-1
    ports:
      - "9001:3306"
    volumes:
      - ./mysql/slave/config_file-slave-1.cnf:/etc/mysql/conf.d/config_file.cnf
    links:
      - mysql-master
